############################# DO NOT EDIT THIS FILE ############################
#
# This is a CMake script for autoinjecting test coverage into your labworks.
# If you're a student and you want to add coverage reports to your own project,
# do NOT use this script.
#
# This script is not meant to be used in production -- it's a collection of
# hacks and heuristics to automatically inject coverage collection into ALL
# targets, determine which source files should be tested, and include them into
# the coverage report.
#
# It's primary goal is to be robust and invisible, not flexible, explicit or
# even correct. Feel free to take inspiration though.
#
# If you want to add coverage reports to your project, see these resources:
#
# 1. https://cmake.org/cmake/help/latest/command/ctest_coverage.html
# 2. https://danielsieger.com/blog/2024/08/03/code-coverage-with-cmake.html
# 3. https://smhk.net/note/2024/11/cmake-and-coverage-with-gcov/
#
################################# ITMO C++ 2025 ################################

cmake_minimum_required(VERSION 3.12)

option(WITH_COVERAGE "Enable coverage generation" OFF)
option(NO_COVERAGE_HTML "Disable coverage HTML reports" OFF)

if(NOT WITH_COVERAGE)
    return()
endif()

if(NOT (CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang"))
    message(FATAL_ERROR "Coverage generation is available only on gcc or clang.")
endif()

if("${CMAKE_SOURCE_DIR}" STREQUAL "${CMAKE_BINARY_DIR}")
    message(FATAL_ERROR "Build and source directories are the same.\n"
        "This will mess with coverage report generation.\n")
endif()


function(_inject_coverage target)
    get_target_property(alias ${target} ALIASED_TARGET)
    if(alias)
        return()
    endif()

    get_target_property(type ${target} TYPE)
    if(type MATCHES "UTILITY")
        message(STATUS "[Coverage] Skipping \"${target}\" (target is ${type})")
        return()
    endif()

    message(STATUS "[Coverage] Injecting coverage generation into \"${target}\"")

    # Yes, public. We want to force-reinject these options EVERYWHERE.
    target_compile_options(${target} PUBLIC --coverage -O0 -g)
    target_link_options(${target} PUBLIC --coverage)
endfunction()


function(_is_test_target target out)
    get_target_property(linked_libs ${target} INTERFACE_LINK_LIBRARIES)
    if(NOT linked_libs)
        get_target_property(linked_libs ${target} LINK_LIBRARIES)
    endif()

    set(linked_to_gtest FALSE)
    foreach(lib IN LISTS linked_libs)
        if(lib MATCHES "^GTest::")
            message(STATUS "[Coverage] Assuming that \"${target}\" is a test target (it's linked to GTest)")
            set(linked_to_gtest TRUE)
            break()
        endif()
    endforeach()

    set(${out} "${linked_to_gtest}" PARENT_SCOPE)
endfunction()


function(_get_target_sources target out)
    get_target_property(target_dir "${target}" SOURCE_DIR)
    if(NOT target_dir)
        set(target_dir ${CMAKE_CURRENT_SOURCE_DIR})
    endif()

    get_target_property(srcs "${target}" SOURCES)

    set(abs_srcs)
    foreach(src IN LISTS srcs)
        if(IS_ABSOLUTE "${src}")
            set(abs_src "${src}")
        else()
            get_filename_component(abs_src "${target_dir}/${src}" ABSOLUTE)
        endif()
        list(APPEND abs_srcs "${abs_src}")
    endforeach()

    set(${out} "${abs_srcs}" PARENT_SCOPE)
endfunction()


# https://gist.github.com/mikedld/a687baabc952a7f061b6a2fd3069f91c
function(_collect_targets dir out)
    get_property(dir_targets DIRECTORY "${dir}" PROPERTY BUILDSYSTEM_TARGETS)
    set(targets)
    foreach(target IN LISTS dir_targets)
        list(APPEND targets "${target}")
    endforeach()

    get_property(subdirs DIRECTORY "${dir}" PROPERTY SUBDIRECTORIES)
    foreach(subdir IN LISTS subdirs)
        _collect_targets("${subdir}" sub_targets)
        list(APPEND targets "${sub_targets}")
    endforeach()

    list(REMOVE_DUPLICATES targets)
    set(${out} "${targets}" PARENT_SCOPE)
endfunction()


function(_generate_gcovr_exclude_args targets out)
    set(args)
    foreach(target IN LISTS targets)
        _is_test_target("${target}" is_test)
        if(NOT is_test)
            continue()
        endif()

        _get_target_sources("${target}" files)
        foreach(file IN LISTS files)
            # Gcovr takes regexes, but we want to pass exact paths,
            # So we'll escape the following symbols: [ ( ) { . ^ $ * + ? \ |
            string(REGEX REPLACE "([\\[(){.^$*+?\\\\|])" "\\\\\\1" regex "${file}")
            list(APPEND args "--exclude" "${regex}")
        endforeach()
    endforeach()

    set(${out} "${args}" PARENT_SCOPE)
endfunction()


function(coverage_finalize)
    _collect_targets(${CMAKE_SOURCE_DIR} targets)

    foreach(target IN LISTS targets)
        _inject_coverage("${target}")
    endforeach()

    _generate_gcovr_exclude_args("${targets}" GCOVR_COVERAGE_EXCLUDE)

    if(NOT NO_COVERAGE_HTML)
        set(HTML_OPTIONS
            --html-self-contained
            # --html-single-page js-enabled <- not yet available on stable versions
            --html-theme green
            --html-details "${CMAKE_BINARY_DIR}/coverage.html"
        )
        set(HTML_REPORT_MESSAGE "Coverage report was saved at ${CMAKE_BINARY_DIR}/coverage.html")
    else()
        set(HTML_OPTIONS)
        set(HTML_REPORT_MESSAGE "HTML report will not be generated.")
    endif()

    add_custom_target(coverage
        COMMENT "Generating coverage report..."
        COMMAND ${CMAKE_CTEST_COMMAND} --output-on-failure || true
        COMMAND gcovr -r "${CMAKE_SOURCE_DIR}" "${CMAKE_BINARY_DIR}"
            --exclude "${CMAKE_BINARY_DIR}"
            ${GCOVR_COVERAGE_EXCLUDE}
            --txt "${CMAKE_BINARY_DIR}/coverage.txt"
            --json-summary "${CMAKE_BINARY_DIR}/coverage.json"
            ${HTML_OPTIONS}
            --gcov-delete
        COMMAND ${CMAKE_COMMAND} -E cmake_echo_color --cyan "${HTML_REPORT_MESSAGE}"
        WORKING_DIRECTORY "${CMAKE_BINARY_DIR}"
        VERBATIM
    )
endfunction()

coverage_finalize()
